// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Tn_qoC21GCxjdClzAdt2_blFZ2lHFXc',
    appId: '1:891266904376:web:5c95756a856c08325891cd',
    messagingSenderId: '891266904376',
    projectId: 'firechat-82847',
    authDomain: 'firechat-82847.firebaseapp.com',
    storageBucket: 'firechat-82847.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQr4PPWvmudyIkXJkaGJZLKhUnOuXWy4M',
    appId: '1:891266904376:android:cf5087d879630e9e5891cd',
    messagingSenderId: '891266904376',
    projectId: 'firechat-82847',
    storageBucket: 'firechat-82847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwxrwoRAvnmF8XUaJTisIKjzUq-UB6tkU',
    appId: '1:891266904376:ios:db87b0af0e5e7d9c5891cd',
    messagingSenderId: '891266904376',
    projectId: 'firechat-82847',
    storageBucket: 'firechat-82847.appspot.com',
    iosClientId: '891266904376-9dgpicr08900bkn06qk2jc4n4jdr3hea.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleflutter',
  );
}
